---
- name: installing and launching metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat>

  - name: install filebeat deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: metricbeat modules enable docker

  - name: setup metribeat
    command: metricbeat setup

  - name: start metricbeat service
    command: service metricbeat start

  - name: run metricbeat command e
    command: metricbeat setup -e

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
















